### ISSUE TITLE
Hiiii!

### ISSUE THREAD

**Issue by jakovyboy** [Lukahn2501/wotv-assets#1]
hi man sorry for ask you about this, but is there anyposible way to get the 3d models?? how you manage to do the extraction? y tried so many times but i dont get any mesh or texture! can you give a hint please?

**Comment by Lukahn2501** [comment]
Hi, 

No worries. Unfortunately I don't know how to do this. 

I remember someone asking once about it on the reddit dicord here https://www.reddit.com/r/wotv_ffbe and they've been linked to this deviantart : https://www.deviantart.com/kittyinhiding/art/FFBE-WAR-OF-THE-VISIONS-831251855?comment=1%3A831251855%3A4847298239

You might want to ask around these two places. :)

As to how I extract it i'm using the tool provided here : https://gitlab.com/war-of-the-visions.
You could also check around https://github.com/shalzuth/wotv-ffbe-dump 

Both of the persons managing those are more knowledgable than me on the subject.

Hope you find what you're looking for!

Have a nice day.
